#ifndef __ENUMS__ECHATCHANNEL_HPP__
#define __ENUMS__ECHATCHANNEL_HPP__

#include <memory>

namespace Enums {
	enum class EChatChannel : std::int32_t {
		CHAT_CHANNEL_SYSTEM_NOTIFY = 0,
		CHAT_CHANNEL_SYSTEM_WARNING = 1,
		CHAT_CHANNEL_SYSTEM_ERROR = 2,
		CHAT_CHANNEL_BROADCAST = 3,
		CHAT_CHANNEL_LOCAL = 4,
		CHAT_CHANNEL_LOCAL_NOANIM = 5,
		CHAT_CHANNEL_EMOTE = 6,
		CHAT_CHANNEL_PRIVATE = 7,
		CHAT_CHANNEL_TEAM = 8,
		CHAT_CHANNEL_TEAM_LOCAL = 9,
		CHAT_CHANNEL_GUILD = 10,
		CHAT_CHANNEL_GUILD_NOTIFY = 11,
		CHAT_CHANNEL_PROPERTY = 12,
		CHAT_CHANNEL_ADMIN = 13,
		CHAT_CHANNEL_COMBAT_DAMAGE = 14,
		CHAT_CHANNEL_COMBAT_HEALING = 15,
		CHAT_CHANNEL_COMBAT_LOOT = 16,
		CHAT_CHANNEL_COMBAT_EXP = 17,
		CHAT_CHANNEL_COMBAT_DEATH = 18,
		CHAT_CHANNEL_GENERAL = 19,
		CHAT_CHANNEL_TRADE = 20,
		CHAT_CHANNEL_LFG = 21,
		CHAT_CHANNEL_USER = 22
	};
}

#endif