#ifndef __MISC__WORLD_CHECKUM_HPP__ 
#define __MISC__WORLD_CHECKUM_HPP__
#include <unordered_map>
#include <memory>

// This file serves the purpose of containing the checksums for the luz files,
// which is required by the client to properly load the map.
// As we currently don't know how this checksum is generated,
// we have to define it statically for now.

// So far we know, that the checksum is only generated by the luz file itself.
// I've made some checks, that the revision, the scene content (needs to be further checked),
// The paths (not sure) and such are checked. Transitions don't affect the checksum.
// IIRC, the zone id was also important, but i guess only the first byte is used, as otherwise,
// the checksum for 1102 and 1150 would be different.

static const std::unordered_map<std::uint16_t, std::uint32_t> WORLD_CHECKSUM = {
	{1000, 0x20b8087c},
	{1001, 0x26680a3c},
	{1100, 0x49525511},
	{1101, 0x538214e2},
	{1102, 0x0fd403da},
	{1150, 0x0fd403da},
	{1151, 0x0a890303},
	{1200, 0xda1e6b30},
	{1201, 0x476e1330},
	{1203, 0x10fc0502},
	{1204, 0x07d40258},
	{1250, 0x058d0191},
	{1251, 0x094f045d},
	{1260, 0xffffffff}, // TODO: Mod client & re checksum. (Don't have it written down yet)
	{1251, 0xffffffff}, // TODO: Mod client & re checksum. (Don't have it written down yet)
	{1300, 0x12eac290},
	{1302, 0x0b7702ef},
	{1303, 0x152e078a},
	{1350, 0x04b6015c},
	{1400, 0x8519760d},
	{1402, 0x02f50187},
	{1403, 0x81850f4e},
	{1450, 0x03f00126},
	{1600, 0x07c202ee},
	{1601, 0x02320106},
	{1602, 0x0793037f},
	{1603, 0x043b01ad},
	{1604, 0x181507dd},
	{1700, 0x02040138},
	{1800, 0x4b17a399},
	{1900, 0x9e4af43c},
	{2000, 0x4d692c74},
	{2001, 0x09eb00ef}
};


#endif
