CREATE TABLE [dbo].[CharacterStats](
	[statsID] [int] NOT NULL,
	[TotalCurrencyCollected] [int] NOT NULL,
	[TotalBricksCollected] [int] NOT NULL,
	[TotalSmashablesSmashed] [int] NOT NULL,
	[TotalQuickBuildsCompleted] [int] NOT NULL,
	[TotalEnemiesSmashed] [int] NOT NULL,
	[TotalRocketsUsed] [int] NOT NULL,
	[TotalPetsTamed] [int] NOT NULL,
	[TotalImaginationPowerUpsCollected] [int] NOT NULL,
	[TotalLifePowerUpsCollected] [int] NOT NULL,
	[TotalArmorPowerUpsCollected] [int] NOT NULL,
	[TotalDistanceTraveled] [int] NOT NULL,
	[TotalSuicides] [int] NOT NULL,
	[TotalDamageTaken] [int] NOT NULL,
	[TotalDamageHealed] [int] NOT NULL,
	[TotalArmorRepaired] [int] NOT NULL,
	[TotalImaginationRestored] [int] NOT NULL,
	[TotalImaginationUsed] [int] NOT NULL,
	[TotalDistanceDriven] [int] NOT NULL,
	[TotalTimeAirborne] [int] NOT NULL,
	[TotalRacingImaginationPowerUpsCollected] [int] NOT NULL,
	[TotalRacecarBoostsActivated] [int] NOT NULL,
	[TotalRacecarWrecks] [int] NOT NULL,
	[TotalRacingSmashablesSmashed] [int] NOT NULL,
	[TotalRacesFinished] [int] NOT NULL,
	[TotalFirstPlaceFinishes] [int] NOT NULL
) ON [PRIMARY]
GO